### ISSUE TITLE
when run detect_multi.py got error: KeyError: u'TensorArrayV3', how to resolve it?

### ISSUE THREAD

**Issue by gangyahaidao** [victordibia/handtracking#12]
Hello guys:
when i run this project get some errors:
ubuntu16.04 
cuda8.0
tensorflow: tensorflow-0.11.0rc1-cp27-none-linux_x86_64.whl
python 2.7.12

```
KeyError: u'TensorArrayV3'
Process PoolWorker-648:
Process PoolWorker-647:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 97, in worker
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 97, in worker
    initializer(*initargs)
  File "detect_multi_threaded.py", line 21, in worker
    initializer(*initargs)
  File "detect_multi_threaded.py", line 21, in worker
    detection_graph, sess = detector_utils.load_inference_graph()
    detection_graph, sess = detector_utils.load_inference_graph()
  File "/home/rosrobot/git/handtracking/utils/detector_utils.py", line 45, in load_inference_graph
  File "/home/rosrobot/git/handtracking/utils/detector_utils.py", line 45, in load_inference_graph
    tf.import_graph_def(od_graph_def, name='')
    tf.import_graph_def(od_graph_def, name='')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 258, in import_graph_def
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 258, in import_graph_def
    op_def = op_dict[node.op]
    op_def = op_dict[node.op]
```

**Comment by gangyahaidao** [comment]
then i reinstall the correct tensorflow and cudnn, then solve the problem, but i get other errors, how sad
