### ISSUE TITLE
using scripts/retrain.py how to proceed?

### ISSUE THREAD

**Issue by monajalal** [victordibia/handtracking#21]
I have a naive question. I followed the Google Collab tutorial for transfer learning on images of 5 categories of flowers. However, how can I do the same for the images of hands from egohands? What are the changes I should perform?

```
mona@Mona:~/code/handpose/handtracking$ IMAGE_SIZE=224
mona@Mona:~/code/handpose/handtracking$ ARCHITECTURE="mobilenet_0.50_${IMAGE_SIZE}"
mona@Mona:~/code/handpose/handtracking$ python -m scripts.retrain   --bottleneck_dir=tf_files/bottlenecks   --how_many_training_steps=500   --model_dir=tf_files/models/   --summaries_dir=tf_files/training_summaries/"${ARCHITECTURE}"   --output_graph=tf_files/retrained_graph.pb   --output_labels=tf_files/retrained_labels.txt   --architecture="${ARCHITECTURE}"   --image_dir=images/train
/home/mona/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
>> Downloading mobilenet_v1_0.50_224_frozen.tgz 100.1%
--- Logging error ---
Traceback (most recent call last):
  File "/home/mona/anaconda3/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/home/mona/anaconda3/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/home/mona/anaconda3/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/home/mona/anaconda3/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/mona/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/mona/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mona/code/handpose/handtracking/scripts/retrain.py", line 1326, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/mona/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/mona/code/handpose/handtracking/scripts/retrain.py", line 982, in main
    maybe_download_and_extract(model_info['data_url'])
  File "/home/mona/code/handpose/handtracking/scripts/retrain.py", line 339, in maybe_download_and_extract
    'bytes.')
  File "/home/mona/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/tf_logging.py", line 116, in info
    _get_logger().info(msg, *args, **kwargs)
Message: 'Successfully downloaded'
Arguments: ('mobilenet_v1_0.50_224_frozen.tgz', 6308169, 'bytes.')
ERROR:tensorflow:No valid folders of images found at images/train

```

It does seem I am not the only one who is needing help with this based on other git issues. Some guidance is really appreciated.

**Comment by victordibia** [comment]
Hi Mona,

Transfer learning for image classification and object detection tasks differ. It seems the flower tutorial you refer to is a classic image classification task, while the hand tracking is an object identification task. I found the [stanford cs231n course](http://cs231n.github.io/) helpful in building an understanding of these tasks.

![image](https://user-images.githubusercontent.com/1547007/41883879-b2f6c038-78be-11e8-95a3-f03e298f5398.png)

Now, regarding training, the work here heavily depends on the Tensorflow Object Detection Api and assumes the reader is familiar with the api. I would suggest running the api code and understanding it.
I also provide provide reference to tutorials I used/followed to do my own "transfer learning". Please see issue #18 

Goodluck!

-V.
