### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by JasOlean** [victordibia/handtracking#24]
Hi, I face an error like this. My tensorflow version is 1.4.0-rc0. how can I solve this? Please help me.

Traceback (most recent call last):
  File "detect_single_threaded.py", line 52, in <module>
    image_np, detection_graph, sess)
  File "/home/khin/models/research/object_detection/utils/detector_utils.py", line 90, in detect_objects
    feed_dict={image_tensor: image_np_expanded})
  File "/home/khin/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/khin/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1089, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "/home/khin/anaconda3/lib/python3.6/site-packages/numpy/core/numeric.py", line 492, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by Jacob12138xieyuan** [comment]
same problem

**Comment by wxyangf** [comment]
I had the same issue, my resolution was to give it the device path and that seemed to work, eg:

Instead of: `python detect_single_threaded.py -src 0`
Try instead: `python detect_single_threaded.py -src /dev/video0`

This is, of course, assuming that you are on Linux and have v4l (Video 4 Linux) and its utilities installed
