### ISSUE TITLE
I can't identify the hand in the picture

### ISSUE THREAD

**Issue by jianghongsun** [victordibia/handtracking#9]
I am very happy to see the report :How to implement real-time hand detection based on SSD neural network.when I in my ubuntu16.04LTS running program. I met such problem:
2018-02-08 14:34:22.983867: E tensorflow/core/common_runtime/executor.cc:643] Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'T' not in Op<name=Where; signature=input:bool -> index:int64>; NodeDef: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan/Where = Where[T=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan/Where/Cast). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan/Where = Where[T=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan/Where/Cast)]]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'T' not in Op<name=Where; signature=input:bool -> index:int64>; NodeDef: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan/Where = Where[T=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan/Where/Cast). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan/Where = Where[T=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan/Where/Cast)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sun/untitled/hhand_rrecognition.py", line 93, in <module>
    boxes,scores=detect_objects(image_np,detection_graph,sess)
  File "/home/sun/untitled/hhand_rrecognition.py", line 81, in detect_objects
    feed_dict={image_tensor: image_np_expanded})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'T' not in Op<name=Where; signature=input:bool -> index:int64>; NodeDef: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan/Where = Where[T=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan/Where/Cast). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan/Where = Where[T=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan/Where/Cast)]]

Caused by op 'Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan/Where', defined at:
  File "/home/sun/untitled/hhand_rrecognition.py", line 92, in <module>
    detection_graph,sess=load_inference_graph()
  File "/home/sun/untitled/hhand_rrecognition.py", line 48, in load_inference_graph
    tf.import_graph_def(od_graph_def, name='')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 313, in import_graph_def
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): NodeDef mentions attr 'T' not in Op<name=Where; signature=input:bool -> index:int64>; NodeDef: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan/Where = Where[T=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan/Where/Cast). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan/Where = Where[T=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan/Where/Cast)]]
 The tensorflow version 1.4.0rc0 GeForce GTX 1050 ,Can you give me some advice?

**Comment by victordibia** [comment]
Hi,

This error is likely due to differences in tensorflow version.
My advice is that you use the checkpoint data I provide and export a frozen graph using your tensorflow version.
There is a discussion on this in issue #1 

The exported model checkpoint is [here](https://github.com/victordibia/handtracking/tree/master/model-checkpoint).
 A tutorial on how to export the frozen graph is [here](https://pythonprogramming.net/testing-custom-object-detector-tensorflow-object-detection-api-tutorial/?completed=/training-custom-objects-tensorflow-object-detection-api-tutorial/) .. 

-V.

**Comment by jianghongsun** [comment]
Thank you for the reply.when I execute the following instructions:
 python3 export_inference_graph.py \
> --input_type image-tensor\
> --pipeline_config_path traning/ssd_mobilenet_v1_coco.config \
> --trained-checkpoint_prefix traning/model.ckpt-200002.data-00000-of-00001 \
> --output-directory NEW
I met such problem:raise AttributeError('Flag --%s must be specified.' % flag_name)
AttributeError: Flag --trained_checkpoint_prefix must be specified.
Can you give me some advice？Looking forward to your reply！

**Comment by jianghongsun** [comment]
Thank you for the reply.when I execute the following instructions:
python3 export_inference_graph.py \

    --input_type image-tensor\
    --pipeline_config_path traning/ssd_mobilenet_v1_coco.config\
    --trained-checkpoint_prefix traning/model.ckpt-200002.data-00000-of-00001\
    --output-directory NEW
    I met such problem:raise AttributeError('Flag --%s must be specified.' % flag_name)
    AttributeError: Flag --trained_checkpoint_prefix must be specified.
  AttributeError: Flag --pipeline_config_path must be specified.

    Can you give me some advice？Looking forward to your reply！

**Comment by jianghongsun** [comment]
I am very happy for your reply.when I execute the following instructions:
python3 export_inference_graph.py \
> --input_type image_tensor\
> --pipeline_config_path traning/ssd_mobilenet_v1_coco.config \
> --trained_checkpoint_prefix traning/model.ckpt-200002.data-00000-of-00001 \
> > --output_directory NEW
I met the problem is that:
Traceback (most recent call last):
  File "export_inference_graph.py", line 119, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 41, in run
    flags_passthrough = f._parse_flags(args=args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/flags.py", line 45, in _parse_flags
    self._assert_all_required()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/flags.py", line 78, in _assert_all_required
    self._assert_required(flag_name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/flags.py", line 74, in _assert_required
    raise AttributeError('Flag --%s must be specified.' % flag_name)
AttributeError: Flag --pipeline_config_path must be specified.
Can you give me some advice? Looking forward to your reply!

**Comment by jianghongsun** [comment]
I am very happy for your reply.when I execute the following instructions:
python3 export_inference_graph.py \

    --input_type image_tensor\
    --pipeline_config_path traning/ssd_mobilenet_v1_coco.config\
    --trained_checkpoint_prefix traning/model.ckpt-200002.data-00000-of-00001 \

        --output_directory NEW
        I met the problem is that:
        Traceback (most recent call last):
        File "export_inference_graph.py", line 119, in
        tf.app.run()
        File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 41, in run
        flags_passthrough = f._parse_flags(args=args)
        File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/flags.py", line 45, in _parse_flags
        self._assert_all_required()
        File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/flags.py", line 78, in _assert_all_required
        self._assert_required(flag_name)
        File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/flags.py", line 74, in _assert_required
        raise AttributeError('Flag --%s must be specified.' % flag_name)
        AttributeError: Flag --pipeline_config_path must be specified.
        Can you give me some advice? Looking forward to your reply!

**Comment by jianghongsun** [comment]
Thank you for your reply! Execute the following instructions:
python3 export_inference_graph.py \
    --input_type image_tensor \
    --pipeline_config_path traning/ssd_mobilenet_v1_coco.config\
    --trained_checkpoint_prefix traning/model.ckpt-200002.data-00000-of-00001\
    --output_directory NEW
I met the problems is that:
Traceback (most recent call last):
  File "export_inference_graph.py", line 119, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "export_inference_graph.py", line 115, in main
    FLAGS.output_directory, input_shape)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/models/research/object_detection/exporter.py", line 422, in export_inference_graph
    is_training=False)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/models/research/object_detection/builders/model_builder.py", line 83, in build
    return _build_ssd_model(model_config.ssd, is_training)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/models/research/object_detection/builders/model_builder.py", line 139, in _build_ssd_model
    is_training)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/models/research/object_detection/builders/model_builder.py", line 107, in _build_ssd_feature_extractor
    pad_to_multiple = feature_extractor_config.pad_to_multiple
AttributeError: 'SsdFeatureExtractor' object has no attribute 'pad_to_multiple'
I have a question which of the three .ckpt files to choose .Thank you for you reply!

**Comment by victordibia** [comment]
All of the ckpt files are for the same checkpoint `model.ckpt-200002`
I recommend you look at the tutorial video in the link I shared (its short), it does a good job of explaining the model export process!

Best!

-V.

**Comment by jianghongsun** [comment]
Thank you very much for your help. I realized the function. I have the problems are  that  whether you test the model  in image set  and what is the accuracy rate?
